packages:
  - packages/*

catalog:
  '@types/node': ^22.15.30
  '@eslint/js': ^9.28.0
  '@typescript-eslint/rule-tester': ^8.33.1
  '@typescript-eslint/utils': ^8.33.1
  'tsdown': ^0.12.7
  'typescript-eslint': ^8.33.1
  'typescript': ~5.8.3
