packages:
  - packages/*

catalog:
  '@types/node': ^22.19.1
  '@eslint/js': ^10.0.0
  '@typescript-eslint/rule-tester': ^8.63.0
  '@typescript-eslint/utils': ^8.63.0
  tsdown: ^0.12.9
  typescript-eslint: ^8.63.0
  typescript: ~5.9.3

onlyBuiltDependencies:
  - unrs-resolver

overrides:
  tmp@<=0.2.3: '>=0.2.4'
